### ISSUE TITLE
Tiles overlay presentation 

### ISSUE THREAD

**Issue by Xippo** [simonh9134/TAVF#12]
If we have  more than a bit text inside the overlay, the text sticks at the border. We need some padding or so

**Comment by Xippo** [comment]
we need also better font-size scaling for this element. You can see in the t3 instance, that in the tablet viewports the full text ist not visible

**Comment by simonh9134** [comment]
Du hast das anscheinend schon gefixed. Allerdings musst du bei den Icons darauf achten, dass sie das richtige Format haben. Ich schicke dir Beispiele per mail.
