### ISSUE TITLE
Anchor Links to Home end on wrong position

### ISSUE THREAD

**Issue by Xippo** [simonh9134/TAVF#2]
I have this behavior with firefox. The problem origin seems to be the map.gif stuff

**Comment by simonh9134** [comment]
I cannot reproduce this bug. The map.gif will be removed for the final template as we replace it with the map API. This should fix the problem

**Comment by Xippo** [comment]
You have checked the TYPO3 integration on FF? Ok if we remove the gif it should be fine. I dont have any information about the swap from gif to iframe map on the Homepage.
